s1=set(map(int,input("enter the values for set1:").split(",")))
s2=set(map(int,input("enter the values for set2:").split(",")))
print(s1)
print(s2)
print("Using intersection")
s3=s1.intersection(s2)
print(s3)
print("Using Union")
s4=s1.union(s2)
print(s4)
print("Using Difference")
s5=s1.difference(s2)
print(s5)
